### ISSUE TITLE
Simulation not loading on full screen

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-substation-automation-lab-nitk#1]
Simulation not loading on full screen

**Comment by sravanthimodepu** [comment]
Simulation links on the Fullscreen were ported incorrectly. Updated the proper links to the full screen in all the simulations of 9 experiments and now the simulations are loading on the fullscreen. There is no simulation in the 1st experiment.

**Comment by sravanthimodepu** [comment]
The links in the full screen are working properly. Hence closing the issue.
