### ISSUE TITLE
Analytics usage is not working

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-substation-automation-lab-nitk#2]
lab_id, lab_name, exp_id, exp_name are not updated in the simulations

**Comment by sravanthimodepu** [comment]
Added the below code in all the simulations of 9 experiments to get the analytics usage:

var lab_id = "ee30"; 
var exp_name = "Control of Group Operated Switches (GOS) from workstation"
var lab_name = "Substation Automation"
var user_id = "%%USER_ID%%"; //get the User ID as a string  
var exp_id = "e99350"

**Comment by sravanthimodepu** [comment]
After updating the ids in the experiment, able to get the analytics usage. Hence closing the issue.
